version: '3.8'

volumes:
  database1:
    driver: 'local'

services:
  web:
    image: nginx
    volumes:
      - .:/var/www/app:cached
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app
      - database

  app:
    build:
      context: ./
      dockerfile: ./docker/dev/php/Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    env_file:
      - ./.env
    depends_on:
      - database
    volumes:
      - .:/var/www/app:cached
      - ./docker/dev/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/dev/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  database:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./docker/dev/databse/:/docker-entrypoint-initdb.d/
      - database1:/var/lib/postgresql/data
    ports: 
     - 5432:5432
    environment:
      POSTGRES_USER: webmaster
      POSTGRES_PASSWORD: webmaster
      POSTGRES_DB: symfony
      PGDATA: /var/lib/postgresql/data/pgdata
